from settings.data_settings import TRAIN_SIZE, VALIDATION_SIZE, TEST_SIZE, GENERATOR_BATCH_SIZE

# compile model
LEARNING_RATE = 1e-5

# train model
EPOCHS = 54
STEPS_PER_EPOCH = TRAIN_SIZE // GENERATOR_BATCH_SIZE
VALIDATION_STEPS = VALIDATION_SIZE // GENERATOR_BATCH_SIZE
TEST_STEPS = TEST_SIZE // GENERATOR_BATCH_SIZE